version: '3.9'

services:
  nginx:
    image: nginx:1.26
    platform: linux/x86_64
    volumes:
      - ./app/:/var/www/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8883:80"
    networks:
      - patternLaravel

  php-fpm:
    build:
      context: docker/php
    volumes:
      - ./app/:/var/www/app
      - ./docker/php/conf.d/zzz-xdebug.ini:/usr/local/etc/php/conf.d/zzz-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: serverName=DockerProject1
    networks:
      - patternLaravel

networks:
  patternLaravel:
    driver: bridge
